<a href="https://colab.research.google.com/github/elliot-linsey/QMUL/blob/main/Data%20Mining/Coursework%204%20pt1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from urllib.request import urlopen
from bs4 import BeautifulSoup

# ECS766 Coursework 4 - Elliot Linsey

## Q1.A

* \<!DOCTYPE html\>, this tag declares to the browser what type of information to expect. All html documents must start with this tag. 
* \<html\>, this tag represents the root of the html document and is the tag in which all of the information within the document is contained (apart from the \<!DOCTYPE html\> tag). 
* \<body\>, this tag defines where the contents such as headings, paragraphs, tables, images and anything else that the user will actually see or interact with are placed within the document. There can be only one body within an html document but it can be split into sections with div elements. 
* \<h1\>, this tag is used to define the heading of the html document and is usually used as the main title. This is because it is the largest heading available in comparison to lesser headings like h2, h3 and so on. 
* \<p\>, this tag defines a paragraph element which is a block of text. If the \<h\> tag is the title, then the \<p\> tag will usually be the paragraph below it.
* \<table\>, this tag defines a table, it must contain one of more of the \<tr\>, \<td\> and \<th\> elements.
* \<thead\>, this defines the head of the table which is where the column headings will be located. 
* \<tbody\>, this defines the body of the table where the data will be located. 
* \<tr\>, this indicates a table row which can contain either data \<td\> or headings \<th\> in this instance. 
* \<th\>, this indicates a table heading which will contain the column headings, usually a child of \<tr\>.
* \<td\>, this indicates table data that will be placed within a row, usually a child of \<tr\> also. 

## Q1.B

In [23]:
url = 'http://eecs.qmul.ac.uk/~emmanouilb/income_table.html'
html = urlopen(url)

In [24]:
soup = BeautifulSoup(html, 'lxml')

In [25]:
th = soup.find_all('th')
headers = []
for header in th:
  headers.append(header.get_text())
headers

['Region', 'Age', 'Income', 'Online Shopper']

In [26]:
td = soup.find_all('td')
rows = []
for row in td:
  rows.append(row.get_text())
rows = np.array(rows)
rows = np.reshape(rows,(10,4))
rows

array([['India', '49', '86400', 'No'],
       ['Brazil', '32', '57600', 'Yes'],
       ['USA', '35', '64800', 'No'],
       ['Brazil', '43', '73200', 'No'],
       ['USA', '45', '', 'Yes'],
       ['India', '40', '69600', 'Yes'],
       ['Brazil', '', '62400', 'No'],
       ['India', '53', '94800', 'Yes'],
       ['USA', '55', '99600', 'No'],
       ['India', '42', '80400', 'Yes']], dtype='<U6')

In [27]:
df = pd.DataFrame(rows,columns=headers)
df

Region Age Income Online Shopper
0   India  49  86400             No
1  Brazil  32  57600            Yes
2     USA  35  64800             No
3  Brazil  43  73200             No
4     USA  45                   Yes
5   India  40  69600            Yes
6  Brazil      62400             No
7   India  53  94800            Yes
8     USA  55  99600             No
9   India  42  80400            Yes

## Q2

In [28]:
url = 'http://eecs.qmul.ac.uk/postgraduate/programmes/'
html = urlopen(url)

In [29]:
soup = BeautifulSoup(html, 'lxml')

In [30]:
th = soup.find_all('th')
headers = []
for header in th:
  headers.append(header.get_text())
headers

['Postgraduate degree programmes', 'Part-time(2 year)', 'Full-time(1 year)']

In [31]:
td = soup.find_all('td')
rows = []
for row in td:
  rows.append(row.get_text())
rows = np.array(rows)
rows = np.reshape(rows,(14,3))
rows2 = []
for x in rows:
  rows2.append(np.char.strip(x,'\xa0'))
rows = rows2
#rows

In [32]:
df2 = pd.DataFrame(rows, columns=headers)
df2

Postgraduate degree programmes Part-time(2 year)  \
0      Advanced Electronic and Electrical Engineering              H60C   
1                             Artificial Intelligence              I4U2   
2                                    Big Data Science              H6J6   
3                                      Computer Games                     
4                                    Computer Science              G4U2   
5                        Computer Science by Research              G4Q2   
6                   Computing and Information Systems              G5U6   
7   Data Science and Artificial Intelligence by Co...                     
8                  Electronic Engineering by Research              H6T6   
9                           Internet of Things (Data)              I1T2   
10         Machine Learning for Visual Data Analytics              H6JZ   
11                          Sound and Music Computing              H6T4   
12             Telecommunication and Wireless Systems              H6JD   
13  Digital and Technology Solutions (Apprenticeship)              I4DA   

   Full-time(1 year)  
0               H60A  
1               I4U1  
2               H6J7  
3               I4U4  
4               G4U1  
5               G4Q1  
6               G5U5  
7               I4U5  
8               H6T5  
9               I1T0  
10              H6JE  
11              H6T8  
12              H6JA  
13

In [33]:
links = []
for row in soup.find_all('td'):
  #print(row.find('a'))
  try:
    links.append(row.find('a').get('href'))
  except AttributeError:
    links.append('')

In [34]:
links = np.array(links)
links = np.reshape(links,(14,3))
#links

In [35]:
df3 = pd.DataFrame(links, columns=['drop', 'Part-time Link', 'Full-time Link'])
df3 = df3.drop('drop',axis=1)
df3 = df2.join(df3)
df3

Postgraduate degree programmes Part-time(2 year)  \
0      Advanced Electronic and Electrical Engineering              H60C   
1                             Artificial Intelligence              I4U2   
2                                    Big Data Science              H6J6   
3                                      Computer Games                     
4                                    Computer Science              G4U2   
5                        Computer Science by Research              G4Q2   
6                   Computing and Information Systems              G5U6   
7   Data Science and Artificial Intelligence by Co...                     
8                  Electronic Engineering by Research              H6T6   
9                           Internet of Things (Data)              I1T2   
10         Machine Learning for Visual Data Analytics              H6JZ   
11                          Sound and Music Computing              H6T4   
12             Telecommunication and Wireless Systems              H6JD   
13  Digital and Technology Solutions (Apprenticeship)              I4DA   

   Full-time(1 year)                                     Part-time Link  \
0               H60A  https://www.qmul.ac.uk/postgraduate/taught/cou...   
1               I4U1  https://www.qmul.ac.uk/postgraduate/taught/cou...   
2               H6J7  https://www.qmul.ac.uk/postgraduate/taught/cou...   
3               I4U4                                                      
4               G4U1  https://www.qmul.ac.uk/postgraduate/taught/cou...   
5               G4Q1  https://www.qmul.ac.uk/postgraduate/taught/cou...   
6               G5U5  https://www.qmul.ac.uk/postgraduate/taught/cou...   
7               I4U5                                                      
8               H6T5  https://www.qmul.ac.uk/postgraduate/taught/cou...   
9               I1T0  https://www.qmul.ac.uk/postgraduate/taught/cou...   
10              H6JE  https://www.qmul.ac.uk/postgraduate/taught/cou...   
11              H6T8  https://www.qmul.ac.uk/postgraduate/taught/cou...   
12              H6JA  https://www.qmul.ac.uk/postgraduate/taught/cou...   
13                    https://www.qmul.ac.uk/postgraduate/taught/cou...   

                                       Full-time Link  
0   https://www.qmul.ac.uk/postgraduate/taught/cou...  
1   https://www.qmul.ac.uk/postgraduate/taught/cou...  
2   https://www.qmul.ac.uk/postgraduate/taught/cou...  
3   https://www.qmul.ac.uk/postgraduate/taught/cou...  
4   https://www.qmul.ac.uk/postgraduate/taught/cou...  
5   https://www.qmul.ac.uk/postgraduate/taught/cou...  
6   https://www.qmul.ac.uk/postgraduate/taught/cou...  
7   https://www.qmul.ac.uk/postgraduate/taught/cou...  
8   https://www.qmul.ac.uk/postgraduate/taught/cou...  
9   https://www.qmul.ac.uk/postgraduate/taught/cou...  
10  https://www.qmul.ac.uk/postgraduate/taught/cou...  
11  https://www.qmul.ac.uk/postgraduate/taught/cou...  
12  https://www.qmul.ac.uk/postgraduate/taught/cou...  
13

## Q3

In [36]:
matrix = np.array([[0.25,0,0.25,0.25,0.25],
                   [0,0.25,0.25,0.25,0.25],
                   [0.5,0.5,0,0,0],
                   [0.5,0.5,0,0,0],
                   [0.5,0.5,0,0,0]])
damping = np.array([[0.825,0.825,0.825,0.825,0.825]]).T
damping

matrix = matrix.T
matrix

array([[0.25, 0.  , 0.5 , 0.5 , 0.5 ],
       [0.  , 0.25, 0.5 , 0.5 , 0.5 ],
       [0.25, 0.25, 0.  , 0.  , 0.  ],
       [0.25, 0.25, 0.  , 0.  , 0.  ],
       [0.25, 0.25, 0.  , 0.  , 0.  ]])

In [37]:
iter_1 = np.matmul(matrix,damping)
iter_2 = np.matmul(matrix,iter_1)
iter_3 = np.matmul(matrix,iter_2)
iter_4 = np.matmul(matrix,iter_3)
iter_5 = np.matmul(matrix,iter_4)
iter_6 = np.matmul(matrix,iter_5)
iter_7 = np.matmul(matrix,iter_6)
iter_8 = np.matmul(matrix,iter_7)
iter_9 = np.matmul(matrix,iter_8)
iter_10 = np.matmul(matrix,iter_9)
iter_11 = np.matmul(matrix,iter_10)
iter_12 = np.matmul(matrix,iter_11)
iter_13 = np.matmul(matrix,iter_12)
iter_14 = np.matmul(matrix,iter_13)
iter_15 = np.matmul(matrix,iter_14)

iter_15

array([[1.18329637],
       [1.18329637],
       [0.58613576],
       [0.58613576],
       [0.58613576]])

In [38]:
damping2 = np.array([[0.9,0.9,0.9,0.9,0.9]]).T

In [39]:
def looper(matrix, damping):
    
    test = np.matmul(matrix,damping)
    if not np.array_equal(np.matmul(matrix,damping), test):
        looper(matrix,test)
    return test

looper(matrix,damping)/5

array([[0.28875],
       [0.28875],
       [0.0825 ],
       [0.0825 ],
       [0.0825 ]])

In [40]:
A = ((1-0.85)/5)+0.85*(1/2+1/2+1/2)

A = 0.03+0.85*(0.5+0.5+0.5)
B = 0.03+0.85*(0.5+0.5+0.5)
0.03+0.85*(0.25+0.25)

0.45499999999999996

In [41]:
((0.175/5)+0.825*(0.25+0.5+0.5+0.5))/5

0.29574999999999996

In [42]:
((0.175/5)+0.825*(0.25+0.25))

0.44749999999999995

In [43]:
(0.15/5)+0.85*(0.227+0.227+0.227)

0.60885