In [9]:
import numpy as np
data=(np.array([1,5]), np.array([3,6]), np.array([4,2]), np.array([3,7]), np.array([5,8]),
                                    np.array([25,31]), np.array([27,33]), np.array([23,25]), np.array([31,28]), np.array([33,31]),
                                    np.array([55,54]), np.array([59,51]), np.array([63,65]), np.array([56,62]), np.array([61,61]))

In [10]:
def ini_centroids(data, k):
        lst = []
        data_len = len(data)
        choices = np.random.choice(range(data_len), size=k, replace=False)
        for i in choices:
            lst.append([data[i]])
        return [i[0] for i in lst]

    
#print(ini_centroids(data=(np.array([1,5]), np.array([3,6]), np.array([2,5])),k=2))
ini_centroids_test = ini_centroids(data=(np.array([1,5]), np.array([3,6]), np.array([4,2]), np.array([3,7]), np.array([5,8]),
                                    np.array([25,31]), np.array([27,33]), np.array([23,25]), np.array([31,28]), np.array([33,31]),
                                    np.array([55,54]), np.array([59,51]), np.array([63,65]), np.array([56,62]), np.array([61,61])),k=2)
print(ini_centroids_test)
def clusters(centroids):
        cluster_vals = []
        for i in range(len(centroids)):
            cluster_vals.append([centroids[i]])
        print(cluster_vals)
        for y in data:
            distances = []
            for i in range(len(cluster_vals)):
                distances.append(np.linalg.norm(y - cluster_vals[i][0]))
            #print(distances)
            idx = distances.index(min(distances))
            cluster_vals[idx].append(y)
        for x in cluster_vals:
            for i in range(len(x)):
                for c in range(len(centroids)):
                    if np.array_equal(x[0], centroids[c]):
                        x.remove(x[0])
                        
        return cluster_vals

print(clusters(ini_centroids_test))

[array([31, 28]), array([33, 31])]
[[array([31, 28])], [array([33, 31])]]
[[array([1, 5]), array([3, 6]), array([4, 2]), array([3, 7]), array([5, 8]), array([25, 31]), array([23, 25]), array([31, 28])], [array([27, 33]), array([33, 31]), array([55, 54]), array([59, 51]), array([63, 65]), array([56, 62]), array([61, 61])]]


In [12]:
def update(clust_vals):
    cluster_means = []
    for x in clust_vals:
        cluster_means.append(sum(x[::])/len(x))
        
    print('means = ' + str(cluster_means))
    return clusters(cluster_means)
    
print(update(clusters(ini_centroids_test)))

[[array([31, 28])], [array([33, 31])]]
means = [array([11.875, 14.   ]), array([50.57142857, 51.        ])]
[[array([11.875, 14.   ])], [array([50.57142857, 51.        ])]]
[[array([1, 5]), array([3, 6]), array([4, 2]), array([3, 7]), array([5, 8]), array([25, 31]), array([27, 33]), array([23, 25]), array([31, 28])], [array([33, 31]), array([55, 54]), array([59, 51]), array([63, 65]), array([56, 62]), array([61, 61])]]


In [13]:
centroids = ini_centroids(data, 2)
print(centroids)
cluster_values = clusters(centroids)
print(cluster_values)
updates1 = update(cluster_values)
updates1

[array([3, 7]), array([56, 62])]
[[array([3, 7])], [array([56, 62])]]
[[array([1, 5]), array([3, 6]), array([4, 2]), array([3, 7]), array([5, 8]), array([25, 31]), array([27, 33]), array([23, 25]), array([31, 28]), array([33, 31])], [array([55, 54]), array([59, 51]), array([63, 65]), array([56, 62]), array([61, 61])]]
means = [array([15.5, 17.6]), array([58.8, 58.6])]
[[array([15.5, 17.6])], [array([58.8, 58.6])]]


[[array([1, 5]),
  array([3, 6]),
  array([4, 2]),
  array([3, 7]),
  array([5, 8]),
  array([25, 31]),
  array([27, 33]),
  array([23, 25]),
  array([31, 28]),
  array([33, 31])],
 [array([55, 54]),
  array([59, 51]),
  array([63, 65]),
  array([56, 62]),
  array([61, 61])]]

In [48]:
class k_means():
    def __init__(self, data, k):
        self.data = data
        self.k = k
    def ini_centroids(self, data, k):
        lst = []
        data_len = len(self.data)
        choices = np.random.choice(range(data_len), size=self.k, replace=False)
        for i in choices:
            lst.append([self.data[i]])
        return [i[0] for i in lst]
        return [i[0] for i in lst]
    def clusters(self,centroids):
        cluster_vals = []
        for i in range(len(centroids)):
            cluster_vals.append([centroids[i]])
        print(cluster_vals)
        for y in self.data:
            distances = []
            for i in range(len(cluster_vals)):
                distances.append(np.linalg.norm(y - cluster_vals[i][0]))
            #print(distances)
            idx = distances.index(min(distances))
            cluster_vals[idx].append(y)
        for x in cluster_vals:
            for i in range(len(x)):
                for c in range(len(centroids)):
                    if np.array_equal(x[0], centroids[c]):
                        x.remove(x[0])
                        
        return cluster_vals
    def update(self,clust_vals):
        cluster_means = []
        for x in clust_vals:
            cluster_means.append(sum(x[::])/len(x))

        print('means = ' + str(cluster_means))
        return clusters(cluster_means)
    def k_means_func(self):
        centroids = ini_centroids(self.data, self.k)
        cluster_values = self.clusters(centroids)
        updates = self.update(cluster_values)
        count = 0
        while updates != self.update(updates):
            count += 1
            updates = self.update(updates)
            print(updates)
        print('It took ' + str(count) + ' cycles!')
        return updates
    def plot(self):
        k_mean = self.k_means_func()
        for i in range(len(k_mean)):
            plt.plot(k_mean[i], [0]*len(k_mean[i]), 'o')
            plt.plot(np.mean(k_mean[i]), [0],'x', markersize=15)
    
        
test = k_means(data, 3)    
test.k_means_func()

[[array([1, 5])], [array([61, 61])], [array([23, 25])]]
means = [array([3.75, 5.75]), array([58.8, 58.6]), array([27.8, 29.6])]
[[array([3.75, 5.75])], [array([58.8, 58.6])], [array([27.8, 29.6])]]
means = [array([3.2, 5.6]), array([58.8, 58.6]), array([27.8, 29.6])]
[[array([3.2, 5.6])], [array([58.8, 58.6])], [array([27.8, 29.6])]]
It took 0 cycles!


[[array([1, 5]), array([3, 6]), array([4, 2]), array([3, 7]), array([5, 8])],
 [array([55, 54]),
  array([59, 51]),
  array([63, 65]),
  array([56, 62]),
  array([61, 61])],
 [array([25, 31]),
  array([27, 33]),
  array([23, 25]),
  array([31, 28]),
  array([33, 31])]]

Having an issue with higher k numbers. 