In [4]:
import numpy as np
data=(np.array([1,5]), np.array([3,6]), np.array([4,2]), np.array([3,7]), np.array([5,8]),
                                    np.array([25,31]), np.array([27,33]), np.array([23,25]), np.array([31,28]), np.array([33,31]),
                                    np.array([55,54]), np.array([59,51]), np.array([63,65]), np.array([56,62]), np.array([61,61]))

In [18]:
class k_means():
    def __init__(self, data, k):
        self.data = data
        self.k = k
    def ini_centroids(self, data, k):
        lst = []
        data_len = len(self.data)
        choices = np.random.choice(range(data_len), size=self.k, replace=False)
        for i in choices:
            lst.append([self.data[i]])
        return [i[0] for i in lst]
    def array_remove(self, base_array, test_array):
        for index in range(len(base_array)):
            if np.array_equal(base_array[index], test_array):
                base_array.pop(index)
            else:
                break
        return base_array
    
    def clusters(self,centroids):
        cluster_vals = []
        #print(cluster_vals)
        for i in range(len(centroids)):
            cluster_vals.append([centroids[i]])
        print(cluster_vals)
        for y in self.data:
            distances = []
            for i in range(len(cluster_vals)):
                distances.append(np.linalg.norm(y - cluster_vals[i][0]))
            #print(distances)
            idx = distances.index(min(distances))
            cluster_vals[idx].append(y)
        for y in centroids:
            cluster_vals = self.array_remove(cluster_vals, y)
                        
        return cluster_vals
    def update(self,clust_vals):
        cluster_means = []
        for x in clust_vals:
            cluster_means.append(sum(x[::])/len(x))

        print('means = ' + str(cluster_means))
        return self.clusters(cluster_means)
    def k_means_func(self):
        centroids = self.ini_centroids(self.data, self.k)
        cluster_values = self.clusters(centroids)
        updates = self.update(cluster_values)
        count = 0
        for i in range(10):
            count += 1
            updates = self.update(updates)
            #print(updates)
        print('It took ' + str(count) + ' cycles!')
        return updates
    def plot(self):
        k_mean = self.k_means_func()
        for i in range(len(k_mean)):
            plt.plot(k_mean[i], [0]*len(k_mean[i]), 'o')
            plt.plot(np.mean(k_mean[i]), [0],'x', markersize=15)
    
        
test = k_means(data, 5)    
test.k_means_func()

[[array([4, 2])], [array([3, 6])], [array([33, 31])], [array([23, 25])], [array([63, 65])]]
means = [array([4., 2.]), array([3. , 6.4]), array([31.  , 30.75]), array([23.66666667, 27.        ]), array([59.5       , 59.66666667])]
[[array([4., 2.])], [array([3. , 6.4])], [array([31.  , 30.75])], [array([23.66666667, 27.        ])], [array([59.5       , 59.66666667])]]
means = [array([4., 2.]), array([3.  , 6.48]), array([30.5   , 30.6875]), array([23.88888889, 27.66666667]), array([58.91666667, 58.77777778])]
[[array([4., 2.])], [array([3.  , 6.48])], [array([30.5   , 30.6875])], [array([23.88888889, 27.66666667])], [array([58.91666667, 58.77777778])]]
means = [array([4., 2.]), array([3.   , 6.496]), array([30.375   , 30.671875]), array([23.96296296, 27.88888889]), array([58.81944444, 58.62962963])]
[[array([4., 2.])], [array([3.   , 6.496])], [array([30.375   , 30.671875])], [array([23.96296296, 27.88888889])], [array([58.81944444, 58.62962963])]]
means = [array([4., 2.]), array([3.   

[[array([4., 2.]), array([4, 2])],
 [array([3.        , 6.49999999]),
  array([1, 5]),
  array([3, 6]),
  array([3, 7]),
  array([5, 8])],
 [array([30.33333397, 30.66666675]),
  array([27, 33]),
  array([31, 28]),
  array([33, 31])],
 [array([23.99999435, 27.99998306]), array([25, 31]), array([23, 25])],
 [array([58.80000001, 58.60000002]),
  array([55, 54]),
  array([59, 51]),
  array([63, 65]),
  array([56, 62]),
  array([61, 61])]]

Having an issue with higher k numbers. 