In [78]:
import numpy as np

In [79]:
x1 = np.load('quiz5_x1_train_A.npy')
#print(x1)
x2 = np.load('quiz5_x2_train_A.npy')
#print(x2)
y = np.load('quiz5_y_train_A.npy')
#y

In [80]:
X = np.column_stack([np.ones(x1.shape), x1, x2])
X

array([[ 1.0000000000, -2.9372441341, -1.0147050281],
       [ 1.0000000000, -0.7409646114, -2.8385520014],
       [ 1.0000000000, -0.9839908064, -2.9980625732],
       [ 1.0000000000, -3.1341498978,  0.9135862295],
       [ 1.0000000000, -1.5031902547, -0.3857957584],
       [ 1.0000000000, -2.0288660747, -0.0736283488],
       [ 1.0000000000, -1.8658024414, -2.9016173157],
       [ 1.0000000000,  0.5333901576, -1.3767320613],
       [ 1.0000000000, -1.1053988085, -3.3517588213],
       [ 1.0000000000, -0.9972248290, -1.5111259552],
       [ 1.0000000000, -1.1571074818, -2.0367895989],
       [ 1.0000000000, -2.5413144122, -1.3610303286],
       [ 1.0000000000, -2.9240786188, -0.4322688080],
       [ 1.0000000000, -0.9759801500, -3.5143730045],
       [ 1.0000000000, -0.7651574183,  2.2934875489],
       [ 1.0000000000, -1.5835789183, -3.3295650200],
       [ 1.0000000000, -0.6010614636, -0.3604181851],
       [ 1.0000000000, -0.1660904359, -1.9826772560],
       [ 1.0000000000, -2.88

In [81]:
w = np.array([0,1,2],ndmin=2).T
w


array([[0],
       [1],
       [2]])

In [82]:
# Returns the predicted labels
def prediction(X, w):
  return 1*(np.dot(X, w) > 0)

# Computes the likelihood
def likelihood(X, w, y):
  return np.prod(y*p(X, w) + (1-y)*(1-p(X, w)))

# Computes the negative log-likelihood
def negLogLikelihood(X, w, y):
  return -np.sum(y * np.log(p(X,w)) + (1 - y) * np.log(1 - p(X,w)))

# Computes the accuracy by comparing true labels y and predicted labels yP
def accuracy(y, yP):
  return np.sum(y==yP)/len(y)

In [83]:
yP = prediction(X, w)
yP

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [84]:
accuracy(y,yP)

0.93

In [85]:
w2 = np.array([0,1,-1],ndmin=2).T
w2

array([[ 0],
       [ 1],
       [-1]])

In [86]:
yP2 = prediction(X,w2)
accuracy(y,yP2)

0.435

In [87]:
print(len(x1))
print(len(x1)*0.435)

200
87.0


In [88]:
def gradNegLogLikelihood(X, w, y):
  return -np.dot(X.T, (y - expit(np.dot(X, w)).reshape(y.shape))).ravel()

In [90]:
import scipy.optimize
np.set_printoptions(formatter={'float': '{: 0.10f}'.format})

# Initial guess
initial_w = np.array([1, -1, 1])

# # The loss function to be minimized (i.e. neg log-likelihood)
# def error_func(w):  
#   return negLogLikelihood(X_train, w, y_train.ravel())

# # The gradient of loss function
# def grad_func(w):
#   return gradNegLogLikelihood(X_train, w, y_train)

# Store the path that the optimisation takes to get to the optimal solution
def make_minimize_cb(path=[]):
    
    def minimize_cb(xk):
        # note that we make a deep copy of xk
        path.append(np.copy(xk))

    return minimize_cb
  
path_ = [initial_w]

# Here is where we run gradient descent
res = scipy.optimize.minimize(fun = error_func, x0 = initial_w, 
                              jac = grad_func, tol=1e-6, 
                              callback=make_minimize_cb(path_))

path = np.array(path_)[:,1:].T
solution_w = res.x.reshape(3,1)
negL = negLogLikelihood(X_train, solution_w, y_train)
gradientL = gradNegLogLikelihood(X_train, solution_w, y_train)


# Here we test our solution using the test dataset
#x1_test = df_test['Attribute_1'].to_numpy().reshape(N,1)
#x2_test = df_test['Attribute_2'].to_numpy().reshape(N,1)
X_test = X
y_test = y


print('Computed optimal weights:\t\t {}'.format(res.x))
print('Optimal loss (negative-log-likelihood):\t {:.4f}'.format(negL))
print('Gradient at the optimum point:\t\t {}'.format(gradientL))
print('Train accuracy:\t\t\t\t {:.2f}'.format(accuracy(y_train, prediction(X_train, solution_w).reshape(101,1))))
print('Test accuracy:\t\t\t\t {:.2f}'.format(accuracy(y_test, prediction(X_test, solution_w).reshape(101,1))))
print('\n\nAnd here are all the intermediate solutions the algorithm visited to get to the optimal solution:\n')
for w in path_:
  print('[w_0, w_1, w_2] = {}'.format(w))

NameError: name 'X_train' is not defined