In [11]:
import numpy as np
from sklearn.metrics import mean_squared_error

In [12]:
x = np.array([1,2,3,4])
y_true = np.array([2,5,8,9])
y_pred = np.array([3,4,5,6])
mean_squared_error(y_true,y_pred)

5.0

In [13]:
X = np.column_stack([np.ones(x.shape), x])
X

array([[1., 1.],
       [1., 2.],
       [1., 3.],
       [1., 4.]])

In [22]:
w3 = np.dot(np.dot(np.linalg.inv(np.dot(X.T, X)), X.T), y_true)
np.round(w3,2)

array([-0. ,  2.4])

In [17]:
np.polyfit(x,y_true,1)

array([2.40000000e+00, 1.77635684e-15])

In [23]:
y = np.array([2,5,8,9])
w = np.polyfit(x,y,1)
np.round(w,2)

array([2.4, 0. ])

In [20]:
p = np.poly1d(w)
print("The mathematical expression of the fitted linear model is : ", p)
print("The coefficients of the model are : ", p.c)

The mathematical expression of the fitted linear model is :   
2.4 x + 1.776e-15
The coefficients of the model are :  [2.40000000e+00 1.77635684e-15]


In [31]:
xs = np.array([[0,3],
              [-2,1],
              [2,1],
              [-4,-1],
              [0,-1],
              [4,-1],
              [-2,-3],
              [2,-3],
              [-2,-5],
               [0,-5],
              [2,-5],
              [0,-7]])
np.mean(xs,axis=0)

array([ 0.        , -2.16666667])

In [35]:
(0+-2+2+-4+0+4+-2+2+-2+0+2+0)/12

0.0

In [34]:
(3+1+1+-1+-1+-1+-3+-3+-5+-5+-5+-7)/12

-2.1666666666666665

In [48]:
from scipy import spatial
centroid1 = np.array([2,7])
centroid2 = np.array([2,4])
centroid4 = np.array([4,1])
spatial.distance.euclidean(centroid1, np.array([0,5]))

2.8284271247461903

In [45]:
dist1 = spatial.distance.euclidean(centroid1, np.array([0,6])) + spatial.distance.euclidean(centroid1, np.array([1,6])) +spatial.distance.euclidean(centroid1, np.array([2,6]))+spatial.distance.euclidean(centroid1, np.array([3,6]))+spatial.distance.euclidean(centroid1, np.array([4,6]))

dist1




8.30056307974577

In [51]:
dist4 = spatial.distance.euclidean(centroid4, np.array([2,1])) + spatial.distance.euclidean(centroid4, np.array([3,1])) +spatial.distance.euclidean(centroid4, np.array([4,1]))+spatial.distance.euclidean(centroid4, np.array([5,1]))+spatial.distance.euclidean(centroid4, np.array([6,1]))

dist4

6.0

In [60]:
from scipy.spatial import distance

c1 = np.array([3,20])
c2 = np.array([3,-13])

distance.euclidean(c2, np.array([0,4]))
#distance.euclidean(c2, np.array([2,3]))

17.26267650163207

In [62]:
xs2 = np.array([[2,1],
               [3,1],
               [4,1],
               [5,1],
               [6,1],
               [2,2],
               [6,2],
               [0,3],
               [2,3],
               [4,3],
               [6,3]])

np.mean(xs2,axis=0)

array([3.63636364, 1.90909091])

In [64]:
xs3 = np.array([[0,4],
               [2,4],
               [4,4],
               [6,4],
               [0,5],
               [4,5],
               [0,6],
               [1,6],
               [2,6],
               [3,6],
               [4,6]])

np.mean(xs3, axis=0)

array([2.36363636, 5.09090909])

In [65]:
xs4 = np.array([[2,1],
               [3,1],
               [4,1],
               [5,1],
               [6,1],
               [2,2],
               [6,2],
               [0,3],
               [2,3],
               [4,3],
               [6,3],
               [0,4],
               [2,4],
               [4,4],
               [6,4],
               [0,5],
               [4,5],
               [0,6],
               [1,6],
               [2,6],
               [3,6],
               [4,6]])
np.mean(xs4,axis=0)

array([3. , 3.5])