In [1]:
import numpy as np
import pandas as pd

In [2]:
x = np.array([2,4,1,3])
y = np.array([1+0.1*4,5+0.1*8,2+0.1*4,2+0.1*4])

In [3]:
y

array([1.4, 5.8, 2.4, 2.4])

In [5]:
w = np.polyfit(x,y,1)
w

array([1.12, 0.2 ])

In [7]:
X = np.column_stack([np.ones(x.shape), x])
X

array([[1., 2.],
       [1., 4.],
       [1., 1.],
       [1., 3.]])

In [8]:
w3 = np.dot(np.dot(np.linalg.inv(np.dot(X.T, X)), X.T), y)
w3

array([0.2 , 1.12])

In [9]:
p = np.poly1d(w)
print("The mathematical expression of the fitted linear model is : ", p)
print("The coefficients of the model are : ", p.c)

The mathematical expression of the fitted linear model is :   
1.12 x + 0.2
The coefficients of the model are :  [1.12 0.2 ]


In [12]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y,p(x))

1.2119999999999997

In [1]:
from scipy import spatial
