In [8]:
import pandas as pd
import numpy as np
from scipy.spatial import distance

In [9]:
df = pd.DataFrame({
    'Pet': ['Bird', 'Cat', 'Dog'],
    'Men': [16,14,15],
    'Women': [10,14,11]
})
df = df.set_index('Pet')
df

Men  Women
Pet             
Bird   16     10
Cat    14     14
Dog    15     11

In [10]:
from scipy.stats import chi2_contingency
chi2_contingency(df)

(0.7619047619047619,
 0.6832104226749481,
 2,
 array([[14.625, 11.375],
        [15.75 , 12.25 ],
        [14.625, 11.375]]))

In [48]:
from scipy.special import logit, expit
logit(0.2)

-1.3862943611198906

In [49]:
expit(np.log(0.5/0.5))

0.5

In [55]:
expit(21)

0.9999999992417439

In [12]:
0.58333333 - (3/12*4/12)

0.49999999666666667

In [13]:
(990/1000*0.05)+(10/1000*1)

0.059500000000000004

In [14]:
((10/1000)*1/0.595)

0.016806722689075633

In [15]:
(0.3*0.5)/0.29

0.5172413793103449

In [16]:
(0.7*0.2)/0.29

0.48275862068965514

In [17]:
51.7+48.3

100.0

In [18]:
vector_A = np.array([1,2,3]).T
vector_B = np.array([1,6,1]).T
vector_C = np.array([2,8,4]).T

unit_vector_A = vector_A / np.linalg.norm(vector_A)
unit_vector_B = vector_B / np.linalg.norm(vector_B)
unit_vector_C = vector_C / np.linalg.norm(vector_C)
dot_product1 = np.dot(unit_vector_A, unit_vector_B)
angle1 = np.arccos(dot_product1)
angle1

0.804199586352679

In [19]:
dot_product2 = np.dot(unit_vector_A, unit_vector_C)
angle2 = np.arccos(dot_product2)
angle2

0.5057368047515303

In [20]:
v1 = [1,1]
v2 = [2,4]
v3 = [5,6]

distance.euclidean(v1,v2) + distance.euclidean(v2,v3)
distance.euclidean(v1,v3)

6.4031242374328485

In [21]:
vector_A + vector_B

array([2, 8, 4])

In [22]:
np.linalg.norm(vector_A) + np.linalg.norm(vector_B)


9.906071389742918

In [23]:
np.linalg.norm(vector_A+vector_B)

9.16515138991168

In [24]:
U = np.array([[11,2],
            [3,7],
            [7,8]])
V = np.array([[21,6,2],
            [3,2,4]])
W = np.array([[1,3],
            [3,5]])

In [25]:
U@V

array([[237,  70,  30],
       [ 84,  32,  34],
       [171,  58,  46]])

In [26]:
V.shape

(2, 3)

In [27]:
W.T

array([[1, 3],
       [3, 5]])

In [28]:
U.T

array([[11,  3,  7],
       [ 2,  7,  8]])

In [29]:
U.T+V

array([[32,  9,  9],
       [ 5,  9, 12]])

In [30]:
W@V

array([[30, 12, 14],
       [78, 28, 26]])

In [31]:
A = np.array([[1,2],
            [2,3]])
B = np.array([[-3,2],
            [2,-1]])
C = np.array([[1,0],
            [0,1]])
B@A

array([[1, 0],
       [0, 1]])

In [32]:
np.linalg.det(A)

-1.0

In [33]:
np.linalg.inv(A)

array([[-3.,  2.],
       [ 2., -1.]])

In [34]:
df2 = pd.DataFrame({
    'P': ['v1','v2','v3'],
    'p(p)': [0.25,0.25,0.5]
})
df3 = pd.DataFrame({
    'Q': ['v1','v2','v3'],
    'p(q)': [0.33,0.33,0.33]
})
df2 = df2.set_index('P')
df2['log(1/p(p))'] = np.log2(1/df2['p(p)'])
df2['H(P)'] = df2['p(p)']*df2['log(1/p(p))']
display(df2)

df3 = df3.set_index('Q')
df3['log(1/p(q))'] = np.log2(1/df3['p(q)'])
df3['H(Q)'] = df3['p(q)']*df3['log(1/p(q))']
df3

p(p)  log(1/p(p))  H(P)
P                          
v1  0.25          2.0   0.5
v2  0.25          2.0   0.5
v3  0.50          1.0   0.5

p(q)  log(1/p(q))      H(Q)
Q                              
v1  0.33     1.599462  0.527822
v2  0.33     1.599462  0.527822
v3  0.33     1.599462  0.527822

In [35]:
print(sum(df2['H(P)']))
print(sum(df3['H(Q)']))

1.5
1.5834674497121084


In [36]:
p_x = 0.250+0.125
p_y = 0.250+0.125
p_nx = 1-(0.250+0.125)
p_ny = 1-(0.250+0.125)
p_x*p_y

0.140625

In [37]:
df4 = pd.DataFrame({
    'x':['x','x','nx','nx'],
    'y':['y','ny','y','ny'],
    'P(x,y)':[0.25, 0.125, 0.125, 0.5]
})
df4

x   y  P(x,y)
0   x   y   0.250
1   x  ny   0.125
2  nx   y   0.125
3  nx  ny   0.500

In [38]:
df4['P(x)*P(y)'] = [p_x*p_y,p_x*p_ny,p_nx*p_y,p_nx*p_ny]
df4['ratio'] = df4['P(x,y)']/df4['P(x)*P(y)']
df4['log2_ratio'] = np.log2(df4['ratio'])
df4['P(x,y)*log2()'] = df4['P(x,y)']*df4['log2_ratio']
display(df4)
sum(df4['P(x,y)*log2()'])

x   y  P(x,y)  P(x)*P(y)     ratio  log2_ratio  P(x,y)*log2()
0   x   y   0.250   0.140625  1.777778    0.830075       0.207519
1   x  ny   0.125   0.234375  0.533333   -0.906891      -0.113361
2  nx   y   0.125   0.234375  0.533333   -0.906891      -0.113361
3  nx  ny   0.500   0.390625  1.280000    0.356144       0.178072

0.1588680058499299

In [39]:
df5 = pd.DataFrame({
    'variables':['x','nx','y','ny'],
    'p':[0.250+0.125,1-(0.250+0.125),0.250+0.125,1-(0.250+0.125)]
})

df5['log(1/p)'] = np.log2(1/df5['p'])
df5['H'] = df5['p']*df5['log(1/p)']
df5

variables      p  log(1/p)         H
0         x  0.375  1.415037  0.530639
1        nx  0.625  0.678072  0.423795
2         y  0.375  1.415037  0.530639
3        ny  0.625  0.678072  0.423795

In [40]:
0.53 + 0.53 - (0.53+0.53)

0.0