In [29]:
import numpy as np
from matplotlib import pyplot as plt

In [30]:
x = np.array([1,2,3,5,7,8,2.5,8],ndmin=2).T
y = np.array([2.2,3.5,3.9,2.9,5.0,6.2,3.0,4.8],ndmin=2).T
x

array([[1. ],
       [2. ],
       [3. ],
       [5. ],
       [7. ],
       [8. ],
       [2.5],
       [8. ]])

In [31]:
x.shape

(8, 1)

In [32]:
X = np.column_stack([np.ones(x.shape), x])
X

array([[1. , 1. ],
       [1. , 2. ],
       [1. , 3. ],
       [1. , 5. ],
       [1. , 7. ],
       [1. , 8. ],
       [1. , 2.5],
       [1. , 8. ]])

In [33]:
w = np.dot(np.dot(np.linalg.inv(np.dot(X.T, X)), X.T), y)
w

array([[2.12120022],
       [0.3980931 ]])

In [34]:
X_quadratic = np.column_stack([np.ones(x.shape),x,x**2])
X_quadratic

array([[ 1.  ,  1.  ,  1.  ],
       [ 1.  ,  2.  ,  4.  ],
       [ 1.  ,  3.  ,  9.  ],
       [ 1.  ,  5.  , 25.  ],
       [ 1.  ,  7.  , 49.  ],
       [ 1.  ,  8.  , 64.  ],
       [ 1.  ,  2.5 ,  6.25],
       [ 1.  ,  8.  , 64.  ]])

In [35]:
w_quadratic = np.dot(np.dot(np.linalg.inv(np.dot(X_quadratic.T, X_quadratic)), X_quadratic.T), y)
w_quadratic

array([[2.7167995 ],
       [0.03485877],
       [0.03821489]])

In [36]:
X_cubic = np.column_stack([np.ones(x.shape),x,x**2,x**3])
X_cubic

array([[  1.   ,   1.   ,   1.   ,   1.   ],
       [  1.   ,   2.   ,   4.   ,   8.   ],
       [  1.   ,   3.   ,   9.   ,  27.   ],
       [  1.   ,   5.   ,  25.   , 125.   ],
       [  1.   ,   7.   ,  49.   , 343.   ],
       [  1.   ,   8.   ,  64.   , 512.   ],
       [  1.   ,   2.5  ,   6.25 ,  15.625],
       [  1.   ,   8.   ,  64.   , 512.   ]])

In [37]:
w_cubic = np.dot(np.dot(np.linalg.inv(np.dot(X_cubic.T, X_cubic)), X_cubic.T), y)
w_cubic

array([[ 0.84346828],
       [ 1.95172897],
       [-0.4743834 ],
       [ 0.03818664]])

In [39]:
y = w_cubic[0] + 6*w_cubic[1] + 6**2*w_cubic[2] + 6**3*w_cubic[3]
y

array([3.7243546])